import { describe, it, expect, vi, beforeEach } from 'vitest';
import { CreatePurchaseOrderUseCase } from './CreatePurchaseOrderUseCase';
import { ApprovePurchaseOrderUseCase } from './ApprovePurchaseOrderUseCase';
import { ReceivePurchaseOrderUseCase } from './ReceivePurchaseOrderUseCase';
import { IPurchaseOrderRepository } from '../../infrastructure/repositories/IPurchaseOrderRepository';
import { PurchaseOrder, PurchaseOrderStatus } from '../../domain/entities/PurchaseOrder';
import { ProcessStockMovementUseCase } from '../inventory/ProcessStockMovementUseCase';

// Mock mocks
const mockRepo = {
  create: vi.fn(),
  findById: vi.fn(),
  approve: vi.fn(),
  updateStatus: vi.fn(),
  update: vi.fn(),
  delete: vi.fn(),
  findByOutletId: vi.fn(),
  findByStatus: vi.fn(),
  findAutoGenerated: vi.fn(),
} as unknown as IPurchaseOrderRepository;

const mockProcessStockMovement = {
  execute: vi.fn(),
} as unknown as ProcessStockMovementUseCase;

describe('Purchases Module', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('CreatePurchaseOrderUseCase', () => {
    it('should create a purchase order successfully', async () => {
      const useCase = new CreatePurchaseOrderUseCase(mockRepo);
      const dto = {
        outletId: 'outlet-1',
        supplier: 'Supplier A',
        lines: [{ ingredientId: 'ing-1', quantity: { value: 10, unit: 'kg' } as any }],
      };

      const expectedOrder = { id: 'po-1', status: PurchaseOrderStatus.DRAFT, ...dto } as any;
      vi.mocked(mockRepo.create).mockResolvedValue(expectedOrder);

      const result = await useCase.execute(dto);

      expect(mockRepo.create).toHaveBeenCalledWith(dto);
      expect(result).toEqual(expectedOrder);
    });
  });

  describe('ApprovePurchaseOrderUseCase', () => {
    it('should approve a draft order', async () => {
      const useCase = new ApprovePurchaseOrderUseCase(mockRepo);
      const order = { id: 'po-1', status: PurchaseOrderStatus.DRAFT } as any;
      vi.mocked(mockRepo.findById).mockResolvedValue(order);
      vi.mocked(mockRepo.approve).mockResolvedValue({
        ...order,
        status: PurchaseOrderStatus.APPROVED,
      });

      await useCase.execute({ orderId: 'po-1', approvedBy: 'user-1' });

      expect(mockRepo.approve).toHaveBeenCalledWith({ orderId: 'po-1', approvedBy: 'user-1' });
    });

    it('should throw error if order not found', async () => {
      const useCase = new ApprovePurchaseOrderUseCase(mockRepo);
      vi.mocked(mockRepo.findById).mockResolvedValue(null);
      await expect(useCase.execute({ orderId: 'po-1', approvedBy: 'user-1' })).rejects.toThrow(
        'Purchase order not found'
      );
    });
  });

  describe('ReceivePurchaseOrderUseCase', () => {
    it('should receive an order and process stock movements', async () => {
      const useCase = new ReceivePurchaseOrderUseCase(mockRepo, mockProcessStockMovement);
      const order = {
        id: 'po-1',
        status: PurchaseOrderStatus.APPROVED,
        outletId: 'outlet-1',
        lines: [
          { ingredientId: 'ing-1', quantity: { value: 10, unit: 'kg' }, unitCost: { amount: 100 } },
        ],
      } as any;

      vi.mocked(mockRepo.findById).mockResolvedValue(order);

      await useCase.execute({ orderId: 'po-1', receivedBy: 'user-1' });

      expect(mockProcessStockMovement.execute).toHaveBeenCalledTimes(1);
      expect(mockRepo.updateStatus).toHaveBeenCalledWith('po-1', PurchaseOrderStatus.RECEIVED);
    });

    it('should throw if order is not approved or sent', async () => {
      const useCase = new ReceivePurchaseOrderUseCase(mockRepo, mockProcessStockMovement);
      const order = { id: 'po-1', status: PurchaseOrderStatus.DRAFT } as any;
      vi.mocked(mockRepo.findById).mockResolvedValue(order);

      await expect(useCase.execute({ orderId: 'po-1', receivedBy: 'user-1' })).rejects.toThrow(
        'Cannot receive order in status draft'
      );
    });
  });
});
