import {
  PurchaseOrder,
  CreatePurchaseOrderDTO,
  ApprovePurchaseOrderDTO,
  PurchaseOrderStatus,
} from '../../entities/PurchaseOrder';

export interface IPurchaseOrderRepository {
  create(dto: CreatePurchaseOrderDTO): Promise<PurchaseOrder>;
  findById(id: string): Promise<PurchaseOrder | null>;
  findByOutletId(outletId: string): Promise<PurchaseOrder[]>;
  findByStatus(outletId: string, status: PurchaseOrderStatus): Promise<PurchaseOrder[]>;
  findAutoGenerated(outletId: string): Promise<PurchaseOrder[]>;
  approve(dto: ApprovePurchaseOrderDTO): Promise<PurchaseOrder>;
  updateStatus(id: string, status: PurchaseOrderStatus): Promise<PurchaseOrder>;
  delete(id: string): Promise<void>;
}
