import { Quantity } from '../value-objects/Quantity';
import { Money } from '../value-objects/Money';

export enum PurchaseOrderStatus {
  DRAFT = 'draft',
  PENDING_APPROVAL = 'pending_approval',
  APPROVED = 'approved',
  SENT = 'sent',
  RECEIVED = 'received',
  CANCELLED = 'cancelled',
}

export interface PurchaseOrderLine {
  ingredientId: string;
  ingredientName: string;
  quantity: Quantity;
  unitCost?: Money;
  totalCost?: Money;
  notes?: string;
}

export interface PurchaseOrder {
  id: string;
  outletId: string;
  orderNumber: string;
  supplier: string;
  status: PurchaseOrderStatus;
  lines: PurchaseOrderLine[];
  subtotal?: Money;
  tax?: Money;
  total?: Money;
  isAutoGenerated: boolean;
  expectedDeliveryDate?: Date;
  actualDeliveryDate?: Date;
  notes?: string;
  createdBy: string;
  approvedBy?: string;
  approvedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatePurchaseOrderDTO {
  outletId: string;
  supplier: string;
  lines: Omit<PurchaseOrderLine, 'ingredientName' | 'totalCost'>[];
  expectedDeliveryDate?: Date;
  notes?: string;
  isAutoGenerated?: boolean;
}

export interface ApprovePurchaseOrderDTO {
  orderId: string;
  approvedBy: string;
}
