// Collection Names
export const COLLECTION_NAMES = {
  INGREDIENTS: 'ingredients',
  RECIPES: 'recipes',
  MENUS: 'menus',
  EVENTS: 'events',
  STAFF: 'staff',
  SUPPLIERS: 'suppliers',
  PURCHASE_ORDERS: 'purchaseOrders',
  WASTE_RECORDS: 'wasteRecords',
  SCHEDULE: 'schedule',
  PCCS: 'pccs',
  HACCP_LOGS: 'haccpLogs',
  HACCP_TASKS: 'haccpTasks',
  HACCP_TASK_COMPLETIONS: 'haccpTaskCompletions',
  PRODUCTION_TASKS: 'productionTasks',
  OUTLETS: 'outlets',
  BATCHES: 'batches',
  FICHAS_TECNICAS: 'fichasTecnicas',
  VERSIONES_FICHAS: 'versionesFichas',
  INVENTORY: 'inventory',
  STOCK_MOVEMENTS: 'stockMovements',
  INGREDIENT_PRICE_HISTORY: 'ingredientPriceHistory',
  NOTIFICATIONS: 'notifications',
  SOCIAL_MANAGER_POSTS: 'socialManagerPosts',
} as const;

// Helper to get collection name only (removed live collection refs)
export const COLLECTIONS = COLLECTION_NAMES;

export const collections = {
  ingredients: COLLECTION_NAMES.INGREDIENTS,
  recipes: COLLECTION_NAMES.RECIPES,
  menus: COLLECTION_NAMES.MENUS,
  events: COLLECTION_NAMES.EVENTS,
  staff: COLLECTION_NAMES.STAFF,
  suppliers: COLLECTION_NAMES.SUPPLIERS,
  purchaseOrders: COLLECTION_NAMES.PURCHASE_ORDERS,
  wasteRecords: COLLECTION_NAMES.WASTE_RECORDS,
  schedule: COLLECTION_NAMES.SCHEDULE,
  pccs: COLLECTION_NAMES.PCCS,
  haccpLogs: COLLECTION_NAMES.HACCP_LOGS,
  haccpTasks: COLLECTION_NAMES.HACCP_TASKS,
  haccpTaskCompletions: COLLECTION_NAMES.HACCP_TASK_COMPLETIONS,
  productionTasks: COLLECTION_NAMES.PRODUCTION_TASKS,
  outlets: COLLECTION_NAMES.OUTLETS,
  batches: COLLECTION_NAMES.BATCHES,
  fichasTecnicas: COLLECTION_NAMES.FICHAS_TECNICAS,
  versionesFichas: COLLECTION_NAMES.VERSIONES_FICHAS,
  inventory: COLLECTION_NAMES.INVENTORY,
  stockMovements: COLLECTION_NAMES.STOCK_MOVEMENTS,
  ingredientPriceHistory: COLLECTION_NAMES.INGREDIENT_PRICE_HISTORY,
  notifications: COLLECTION_NAMES.NOTIFICATIONS,
  socialManagerPosts: COLLECTION_NAMES.SOCIAL_MANAGER_POSTS,
};
