export const TYPES = {
  AuthRepository: Symbol.for('AuthRepository'),
  SupabaseAuthRepository: Symbol.for('SupabaseAuthRepository'),
  LoginUseCase: Symbol.for('LoginUseCase'),
  LoginWithEmailUseCase: Symbol.for('LoginWithEmailUseCase'),

  // Ingredients Module
  IngredientRepository: Symbol.for('IngredientRepository'),
  FirebaseIngredientRepository: Symbol.for('FirebaseIngredientRepository'),
  SupabaseIngredientRepository: Symbol.for('SupabaseIngredientRepository'),
  HybridIngredientRepository: Symbol.for('HybridIngredientRepository'),
  CoreIngredientRepository: Symbol.for('CoreIngredientRepository'), // Core interface
  RecipeRepository: Symbol.for('RecipeRepository'),
  FirebaseRecipeRepository: Symbol.for('FirebaseRecipeRepository'),
  SupabaseRecipeRepository: Symbol.for('SupabaseRecipeRepository'),
  CoreRecipeRepository: Symbol.for('CoreRecipeRepository'),
  SupplierRepository: Symbol.for('SupplierRepository'),
  SupabaseSupplierRepository: Symbol.for('SupabaseSupplierRepository'),
  SupabasePurchasingRepository: Symbol.for('SupabasePurchasingRepository'),
  SupabaseProductionRepository: Symbol.for('SupabaseProductionRepository'),
  AIService: Symbol.for('AIService'),
  ImportService: Symbol.for('ImportService'),

  // Ingredients Use Cases
  GetIngredientsUseCase: Symbol.for('GetIngredientsUseCase'),
  CoreGetIngredientsUseCase: Symbol.for('CoreGetIngredientsUseCase'),
  CreateIngredientUseCase: Symbol.for('CreateIngredientUseCase'),
  CoreCreateIngredientUseCase: Symbol.for('CoreCreateIngredientUseCase'),
  UpdateIngredientUseCase: Symbol.for('UpdateIngredientUseCase'),
  CoreUpdateIngredientUseCase: Symbol.for('CoreUpdateIngredientUseCase'),
  DeleteIngredientUseCase: Symbol.for('DeleteIngredientUseCase'),
  CoreDeleteIngredientUseCase: Symbol.for('CoreDeleteIngredientUseCase'),
  EnrichIngredientUseCase: Symbol.for('EnrichIngredientUseCase'),
  ScanDocumentUseCase: Symbol.for('ScanDocumentUseCase'),
  ImportIngredientsUseCase: Symbol.for('ImportIngredientsUseCase'),

  // Recipe Use Cases
  CalculateRecipeCostUseCase: Symbol.for('CalculateRecipeCostUseCase'),
  CoreCalculateRecipeCostUseCase: Symbol.for('CoreCalculateRecipeCostUseCase'),
  GetRecipesUseCase: Symbol.for('GetRecipesUseCase'),
  CoreGetRecipesUseCase: Symbol.for('CoreGetRecipesUseCase'),
  CreateRecipeUseCase: Symbol.for('CreateRecipeUseCase'),
  CoreCreateRecipeUseCase: Symbol.for('CoreCreateRecipeUseCase'),
  UpdateRecipeUseCase: Symbol.for('UpdateRecipeUseCase'),
  CoreUpdateRecipeUseCase: Symbol.for('CoreUpdateRecipeUseCase'),
  DeleteRecipeUseCase: Symbol.for('DeleteRecipeUseCase'),
  CoreDeleteRecipeUseCase: Symbol.for('CoreDeleteRecipeUseCase'),

  InventoryRepository: Symbol.for('InventoryRepository'),
  BatchRepository: Symbol.for('BatchRepository'),
  StockTransactionRepository: Symbol.for('StockTransactionRepository'),
  SupabaseStockTransactionRepository: Symbol.for('SupabaseStockTransactionRepository'),
  TransactionManager: Symbol.for('TransactionManager'),
  RegisterStockMovementUseCase: Symbol.for('RegisterStockMovementUseCase'),
  CoreProcessStockMovementUseCase: Symbol.for('CoreProcessStockMovementUseCase'),
  GetInventoryStatusUseCase: Symbol.for('GetInventoryStatusUseCase'),
  CoreGetInventoryStatusUseCase: Symbol.for('CoreGetInventoryStatusUseCase'),
  PerformAuditUseCase: Symbol.for('PerformAuditUseCase'),
  CorePerformAuditUseCase: Symbol.for('CorePerformAuditUseCase'),
  AddBatchUseCase: Symbol.for('AddBatchUseCase'),
  ConsumeFIFOUseCase: Symbol.for('ConsumeFIFOUseCase'),
  CheckExpiryUseCase: Symbol.for('CheckExpiryUseCase'),
  AdjustStockUseCase: Symbol.for('AdjustStockUseCase'),

  // Analytics Module
  CalculateBCGMatrixUseCase: Symbol.for('CalculateBCGMatrixUseCase'),
  GenerateProfitabilityReportUseCase: Symbol.for('GenerateProfitabilityReportUseCase'),

  // Schedule & Events Module
  ShiftRepository: Symbol.for('ShiftRepository'),
  EventRepository: Symbol.for('EventRepository'),
  EmployeeRepository: Symbol.for('EmployeeRepository'),
  GenerateScheduleUseCase: Symbol.for('GenerateScheduleUseCase'),
  ParseMatrixPlaningUseCase: Symbol.for('ParseMatrixPlaningUseCase'),
  PARSE_SERVICE_SHEET_USE_CASE: Symbol.for('ParseServiceSheetUseCase'),
  SCAN_SPORTS_MENU_USE_CASE: Symbol.for('ScanSportsMenuUseCase'),
  CALCULATE_REQUIREMENTS_USE_CASE: Symbol.for('CalculateRequirementsUseCase'),
  SYNC_SPORTS_MENU_USE_CASE: Symbol.for('SyncSportsMenuUseCase'),
  PRODUCTION_REPOSITORY: Symbol.for('IProductionRepository'),
  PURCHASING_REPOSITORY: Symbol.for('IPurchasingRepository'),
  GetScheduleUseCase: Symbol.for('GetScheduleUseCase'),
  GetEventsUseCase: Symbol.for('GetEventsUseCase'),
  ImportEventsUseCase: Symbol.for('ImportEventsUseCase'),

  // Employee Module
  GetEmployeesUseCase: Symbol.for('GetEmployeesUseCase'),
  SaveEmployeeUseCase: Symbol.for('SaveEmployeeUseCase'),
  DeleteEmployeeUseCase: Symbol.for('DeleteEmployeeUseCase'),

  // User Management Module
  UserRepository: Symbol.for('UserRepository'),
  ListUsersUseCase: Symbol.for('ListUsersUseCase'),
  UpdateUserUseCase: Symbol.for('UpdateUserUseCase'),
  ActivateUserUseCase: Symbol.for('ActivateUserUseCase'),
  DeactivateUserUseCase: Symbol.for('DeactivateUserUseCase'),
  DeleteUserUseCase: Symbol.for('DeleteUserUseCase'),
  AssignOutletsUseCase: Symbol.for('AssignOutletsUseCase'),
  ChangeUserRoleUseCase: Symbol.for('ChangeUserRoleUseCase'),
  InviteUserUseCase: Symbol.for('InviteUserUseCase'),
  ListInvitationsUseCase: Symbol.for('ListInvitationsUseCase'),
  DeleteInvitationUseCase: Symbol.for('DeleteInvitationUseCase'),
};
